/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 *
 * NOTE ON OPTIONAL FIELDS:
 * The OpenAPI spec declares no `required:` arrays, so every property below is marked
 * optional (?). This faithfully reflects the backend's contract — it performs no
 * field validation and inserts straight to the database. The application's own
 * required-field rules live in Zod schemas under web/src/lib/validation/, not here.
 *
 * NOTE ON DefaultResponse:
 * The spec defines DefaultResponse in components/schemas, but web/src/types/api.ts
 * already declares it. That declaration is canonical and imported by this generated
 * file as needed. This file does not re-emit it to avoid duplication.
 */

/**
 * A single animal record as returned by the backend.
 * Fields are all optional per spec — the application enforces its own required-field
 * rules via Zod validation.
 */
export interface AnimalRead {
  Id?: number;
  Name?: string;
  Species?: string;
  Age?: number;
  HabitatId?: number;
  /**
   * Joined from Habitat on read — never written by the client.
   * Because the backend uses an INNER JOIN, an animal whose HabitatId matches
   * no habitat is dropped from list results entirely.
   */
  HabitatName?: string;
  Diet?: string;
  LastChangedUser?: string;
  /**
   * Pre-formatted text, already converted from UTC to South Africa Standard Time
   * by the backend. Display verbatim — never re-parse as UTC or convert again.
   */
  LastChangedDate?: string;
}

/**
 * Response body of GET /v1/animals.
 */
export interface AnimalReadList {
  Animals?: AnimalRead[];
}

/**
 * Request body shape for POST /v1/animals and PUT /v1/animals/{Id}.
 * These are the only writable fields. Id, HabitatName, and LastChangedDate/LastChangedUser
 * are never sent by the client. LastChangedUser is injected as an HTTP header by the
 * server tier, not as a body field.
 */
export interface AnimalWrite {
  Name?: string;
  Species?: string;
  Age?: number;
  HabitatId?: number;
  Diet?: string;
}

/**
 * A single habitat record.
 * Fields are all optional per spec.
 */
export interface HabitatRead {
  Id?: number;
  Name?: string;
  LastChangedUser?: string;
  /**
   * Pre-formatted text, already converted from UTC to South Africa Standard Time.
   * Display verbatim — never re-parse as UTC or convert again.
   */
  LastChangedDate?: string;
}

/**
 * Response body of GET /v1/habitats.
 */
export interface HabitatReadList {
  Habitats?: HabitatRead[];
}
